// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AnimationSpec = { 
/**
 * "fade" | "slide_left" | "slide_right" | "slide_up" | "slide_down" |
 * "karaoke" | "popup" | "none"
 */
kind: string, duration_ms: number, per_word_delay_ms: number, };
