// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options that steer a transcription run. Built from the project's
 * language + context/glossary (the glossary→initial_prompt assembly is
 * Phase 3.4; the field is here so the plumbing exists).
 */
export type AsrOptions = { 
/**
 * ISO 639-1 or "auto" for language autodetect.
 */
language: string, 
/**
 * Whisper beam size — higher = more accurate, slower. Default 5.
 */
beam_size: number, 
/**
 * Bias recognition toward these terms (Whisper initial_prompt /
 * AssemblyAI word_boost / Deepgram keywords). Phase 3.4 populates it.
 */
priming_terms: Array<string>, 
/**
 * Freeform context sentence prepended to the initial_prompt.
 */
context_description: string | null, };
