// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Encoder } from "./Encoder";
import type { VideoCodec } from "./VideoCodec";

export type BurnInOptions = { codec: VideoCodec, encoder: Encoder, 
/**
 * Target output width; `None` keeps source width.
 */
out_width: number | null, 
/**
 * Target output height; `None` keeps source height.
 */
out_height: number | null, 
/**
 * Constant-quality/bitrate hint, in kbps. `None` = encoder default.
 */
bitrate_kbps: number | null, 
/**
 * Render only `[start_ms, end_ms]` (clip). `None` = whole video.
 */
clip_start_ms: bigint | null, clip_end_ms: bigint | null, };
