// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Word } from "./Word";

export type Caption = { id: string, start_ms: number, end_ms: number, words: Array<Word>, speaker_id: string | null, style_id: string | null, notes: string | null, ai_generated: boolean, last_edited_at: number, };
