// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Claude models Verbatim offers for AI features. Haiku is the default
 * for high-volume passes (polish over a whole project); Sonnet/Opus are
 * available when the user wants maximum quality on hard content.
 */
export type ClaudeModel = "haiku45" | "sonnet46" | "opus47";
