// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A social-media clip carved out of the talk (Phase: SundayEdit clips).
 * `caption_ids` are the source captions the clip covers; `start_ms`/`end_ms`
 * are derived from those captions' real timings (never model-invented). The
 * `title` is the clip's main point, rendered as a large on-screen overlay.
 */
export type Clip = { id: string, 
/**
 * The main point — shown as a large title overlay on the clip.
 */
title: string, 
/**
 * One-line summary / hook for the clip.
 */
hook: string, 
/**
 * Source captions this clip covers.
 */
caption_ids: Array<string>, start_ms: number, end_ms: number, };
