// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Clip } from "./Clip";

/**
 * The AI's proposed plan — a talk summary plus the reviewable clips.
 */
export type ClipPlan = { talk_summary: string, clips: Array<Clip>, };
