// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CloudProvider } from "./CloudProvider";

/**
 * A pre-submit cost preview, per the plan's cost-transparency requirement.
 */
export type CloudCostEstimate = { provider: CloudProvider, minutes: number, estimated_usd: number, };
