// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Encoder } from "./Encoder";
import type { VideoCodec } from "./VideoCodec";

/**
 * Output settings for a compose render. Mirrors the knobs `BurnInOptions`
 * exposes, but the compose engine always targets fixed output dimensions +
 * frame rate (the timeline is flattened onto that canvas).
 */
export type ComposeSettings = { width: number, height: number, fps: number, codec: VideoCodec, encoder: Encoder, 
/**
 * Constant-bitrate hint, in kbps. `None` = encoder default.
 */
bitrate_kbps: number | null, };
