// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Streamed to the UI as the compose render advances. Mirrors the reel/download
 * progress shape: a completed fraction over the total timeline duration.
 */
export type ComposeProgress = { 
/**
 * Milliseconds of output rendered so far (from ffmpeg `out_time_ms`).
 */
out_ms: number, 
/**
 * Total timeline duration in ms.
 */
total_ms: number, 
/**
 * 0..1, clamped; `None` when total is 0.
 */
fraction: number | null, 
/**
 * Latest encoded frame count, if ffmpeg reported it.
 */
frame: number, 
/**
 * True on the final tick.
 */
done: boolean, };
