// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Streamed to the UI as a model download progresses.
 */
export type DownloadProgress = { downloaded_bytes: number, 
/**
 * Total size from the server's Content-Length, or null if it didn't
 * send one (then the bar is indeterminate).
 */
total_bytes: number | null, 
/**
 * 0..1 when the total is known, else null.
 */
fraction: number | null, };
