// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A processing effect applied to a timeline item. `params` is an opaque JSON
 * bag keyed by effect `kind`.
 */
export type Effect = { id: string, kind: string, params: unknown, enabled: boolean, };
