// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hardware encoder family — chosen automatically per platform, but
 * overridable (e.g. force CPU for determinism).
 */
export type Encoder = "cpu" | "video-toolbox" | "nvenc" | "quick-sync";
