// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A validation finding shown before rendering.
 */
export type ExportWarning = { 
/**
 * `error` blocks export; `warning` is advisory.
 */
severity: string, message: string, };
