// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Aspect } from "./Aspect";
import type { VideoCodec } from "./VideoCodec";

export type ExportPreset = { id: string, name: string, description: string, aspect: Aspect, width: number, height: number, 
/**
 * Platform's hard max video length in seconds (`None` = no limit).
 */
max_duration_sec: bigint | null, codec: VideoCodec, 
/**
 * Recommended video bitrate (kbps).
 */
bitrate_kbps: number, 
/**
 * Whether we also write an SRT sidecar (good for SEO/accessibility).
 */
also_srt_sidecar: boolean, };
