// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result handed back to the renderer after a successful extraction.
 */
export type ExtractedDocument = { 
/**
 * File name only (no path) — for display.
 */
file_name: string, 
/**
 * Which extractor ran: `"text"` or `"docx"`.
 */
format: string, 
/**
 * The extracted text, already truncated to the prompt budget.
 */
text: string, 
/**
 * Character count of `text` (post-truncation).
 */
char_count: number, 
/**
 * True when the source was longer than `MAX_DOC_CHARS` and got cut.
 */
truncated: boolean, };
