// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FillerHit = { caption_id: string, word_index: number, text: string, start_ms: number, end_ms: number, };
