// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FindMatch = { caption_id: string, word_index: number, 
/**
 * Char offsets of the match within the word's text.
 */
start: number, end: number, 
/**
 * The matched substring (for preview).
 */
matched: string, };
