// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FindOptions = { query: string, case_sensitive: boolean, whole_word: boolean, 
/**
 * Treat `query` as a regular expression.
 */
regex: boolean, };
