// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlossaryCorrection } from "./GlossaryCorrection";
import type { Project } from "./Project";

/**
 * Result of a glossary auto-correction pass: the new project plus the
 * list of corrections so the UI can show "we fixed 4 terms — review?".
 */
export type GlossaryApplyResult = { project: Project, corrections: Array<GlossaryCorrection>, };
