// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GlossaryTerm = { id: string, 
/**
 * Canonical form — what we want in the final output.
 */
term: string, 
/**
 * Likely misrecognitions to auto-correct to `term`.
 */
aliases: Array<string>, definition: string | null, pronunciation_hint: string | null, };
