// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaKind } from "./MediaKind";

/**
 * A validated request to import a media file and seed its captioning context,
 * parsed from a `sundayedit://import?…` deep link. The renderer turns this
 * into a real project via the normal import + context/glossary flows.
 *
 * This is the app-facing, `ts-rs`-exported projection of the canonical
 * [`MediaHandoff`]; it carries the full superset of handoff fields so Rec → Edit
 * (and future Edit → other) handoffs lose nothing.
 */
export type ImportRequest = { 
/**
 * Absolute path to the source video/audio file. Always present.
 */
path: string, 
/**
 * Whether the caller flagged this as video or audio-only, if specified.
 * Maps the canonical `video`/`audio` wire kinds onto SundayEdit's own
 * `Video`/`AudioOnly` media classification.
 */
media_kind: MediaKind | null, 
/**
 * ISO language code to transcribe in, if the caller specified one.
 */
language: string | null, 
/**
 * Free-text priming for context-aware recognition (killer feature #2).
 */
context: string | null, 
/**
 * Glossary terms to seed (speaker names, jargon) — de-duplicated,
 * order preserved.
 */
glossary: Array<string>, 
/**
 * SundayPlan service the media belongs to, if the caller knows it.
 */
service_id: string | null, 
/**
 * Church / tenant id the media belongs to, if the caller knows it.
 */
church_id: string | null, 
/**
 * Scheme of the app that launched us, so we can hand results back
 * (e.g. `"sundayrec"`). `None` for a plain user-initiated link.
 */
return_to: string | null, };
