// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A validated request to import a video and seed its captioning context,
 * parsed from a `sundayedit://import?…` deep link. The renderer turns this
 * into a real project via the normal import + context/glossary flows.
 */
export type ImportRequest = { 
/**
 * Absolute path to the source video/audio file. Always present.
 */
path: string, 
/**
 * ISO language code to transcribe in, if the caller specified one.
 */
language: string | null, 
/**
 * Free-text priming for context-aware recognition (killer feature #2).
 */
context: string | null, 
/**
 * Glossary terms to seed (speaker names, jargon) — de-duplicated,
 * order preserved.
 */
glossary: Array<string>, 
/**
 * Scheme of the app that launched us, so we can hand results back
 * (e.g. `"sundayrec"`). `None` for a plain user-initiated link.
 */
return_to: string | null, };
