/**
 * Type bindings auto-generated by `ts-rs` from Rust models in
 * `src-tauri/src/model.rs`. Regenerate via `cargo test export_bindings`.
 */

export type { AlternateRead } from "./AlternateRead";
export type { AnimationSpec } from "./AnimationSpec";
export type { Caption }       from "./Caption";
export type { GlossaryTerm }  from "./GlossaryTerm";
export type { Project }       from "./Project";
export type { Speaker }       from "./Speaker";
export type { Style }         from "./Style";
export type { Word }          from "./Word";

/** Error shape returned by every Tauri command (see error.rs). */
export interface AppError {
  code:
    | "database" | "migration" | "not_found" | "invariant"
    | "validation" | "io" | "json" | "video_missing" | "internal";
  message: string;
}

/** Confidence tier for a word — drives the highlight color in the editor. */
export type ConfidenceTier = 1 | 2 | 3 | 4;

/** Compute a word's confidence tier — mirrors Word::confidence_tier() in Rust.
 *  Locked or edited words are always tier 1 (no highlight). */
export function confidenceTier(word: {
  confidence: number;
  edited: boolean;
  locked: boolean;
}): ConfidenceTier {
  if (word.locked || word.edited) return 1;
  if (word.confidence >= 85) return 1;
  if (word.confidence >= 70) return 2;
  if (word.confidence >= 50) return 3;
  return 4;
}
