/**
 * Type bindings auto-generated by `ts-rs` from Rust models in
 * `src-tauri/src/model.rs`. Regenerate via `cargo test export_bindings`.
 */

export type { AlternateRead }    from "./AlternateRead";
export type { AnimationSpec }    from "./AnimationSpec";
export type { AsrOptions }       from "./AsrOptions";
export type { Aspect }           from "./Aspect";
export type { BurnInOptions }    from "./BurnInOptions";
export type { Caption }          from "./Caption";
export type { DownloadProgress } from "./DownloadProgress";
export type { Encoder }          from "./Encoder";
export type { ExportPreset }     from "./ExportPreset";
export type { ExportWarning }    from "./ExportWarning";
export type { VideoCodec }       from "./VideoCodec";
export type { CloudProvider }    from "./CloudProvider";
export type { ClaudeModel }      from "./ClaudeModel";
export type { FillerHit }        from "./FillerHit";
export type { FindMatch }        from "./FindMatch";
export type { FindOptions }      from "./FindOptions";
export type { GlossaryCorrection } from "./GlossaryCorrection";
export type { GlossaryApplyResult } from "./GlossaryApplyResult";
export type { GlossaryTerm }     from "./GlossaryTerm";
export type { LengthWarning }    from "./LengthWarning";
export type { MediaKind }        from "./MediaKind";
export type { PolishChange }     from "./PolishChange";
export type { PolishEstimate }   from "./PolishEstimate";
export type { PolishResult }     from "./PolishResult";
export type { ReplaceResult }    from "./ReplaceResult";
export type { SilenceGap }       from "./SilenceGap";
export type { Peak }             from "./Peak";
export type { Project }          from "./Project";
export type { SecretProvider }   from "./SecretProvider";
export type { SecretStatus }     from "./SecretStatus";
export type { Segment }          from "./Segment";
export type { Speaker }          from "./Speaker";
export type { Strictness }       from "./Strictness";
export type { Suggestion }       from "./Suggestion";
export type { SuggestionKind }   from "./SuggestionKind";
export type { Style }            from "./Style";
export type { StylePreset }      from "./StylePreset";
export type { TranscribeProgress } from "./TranscribeProgress";
export type { TranscribedWord }  from "./TranscribedWord";
export type { Transcript }       from "./Transcript";
export type { TranslationLanguage } from "./TranslationLanguage";
export type { TranslationResult } from "./TranslationResult";
export type { VideoMetadata }    from "./VideoMetadata";
export type { WaveformData }     from "./WaveformData";
export type { WhisperModel }     from "./WhisperModel";
export type { WhisperModelInfo } from "./WhisperModelInfo";
export type { Word }             from "./Word";

/** Error shape returned by every Tauri command (see error.rs). */
export interface AppError {
  code:
    | "database" | "migration" | "not_found" | "invariant"
    | "validation" | "io" | "json" | "network" | "video_missing" | "internal";
  message: string;
}

/** Confidence tier for a word — drives the highlight color in the editor. */
export type ConfidenceTier = 1 | 2 | 3 | 4;

/** Compute a word's confidence tier — mirrors Word::confidence_tier() in Rust.
 *  Locked or edited words are always tier 1 (no highlight). */
export function confidenceTier(word: {
  confidence: number;
  edited: boolean;
  locked: boolean;
}): ConfidenceTier {
  if (word.locked || word.edited) return 1;
  if (word.confidence >= 85) return 1;
  if (word.confidence >= 70) return 2;
  if (word.confidence >= 50) return 3;
  return 4;
}
