// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Flagged when a translated caption is much longer than its source, so
 * the reading speed may be too high for its display span.
 */
export type LengthWarning = { caption_id: string, original_chars: number, translated_chars: number, };
