// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaKind } from "./MediaKind";

/**
 * An imported source media file. The `content_hash` gives path-stable identity
 * (same as the scalar `video_content_hash`); `audio_wav_path` caches the
 * extracted PCM used for waveform + ASR.
 */
export type MediaItem = { id: string, path: string, content_hash: string, kind: MediaKind, duration_ms: number, width: number, height: number, fps: number, has_audio: boolean, audio_wav_path: string | null, original_filename: string, added_at: number, };
