// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One vertical slice of the waveform: the min and max sample in a bucket.
 * Rendering draws a vertical line from `min` to `max` per pixel column.
 */
export type Peak = { min: number, max: number, };
