// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PolishEstimate = { caption_count: number, estimated_input_tokens: number, estimated_output_tokens: number, estimated_cost_usd: number, model_id: string, };
