// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One applied punctuation/casing change — surfaced so the user can review,
 * compare against the original ("Show original"), or undo.
 */
export type PolishChange = { caption_id: string, word_index: number, from: string, to: string, };
