// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolishChange } from "./PolishChange";
import type { Project } from "./Project";

/**
 * Result of applying polish: the updated project, the per-word changes,
 * and the ids of any captions whose polish was rejected by the substance
 * guard (the model tried to alter word content — we kept the original).
 */
export type PolishResult = { project: Project, changes: Array<PolishChange>, rejected: Array<string>, };
