// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Caption } from "./Caption";
import type { Clip } from "./Clip";
import type { ExportConfig } from "./ExportConfig";
import type { GlossaryTerm } from "./GlossaryTerm";
import type { ProjectMeta } from "./ProjectMeta";
import type { Speaker } from "./Speaker";
import type { Style } from "./Style";

export type Project = { id: string, name: string, video_path: string, video_content_hash: string, video_duration_ms: number, video_width: number, video_height: number, video_fps: number, audio_wav_path: string | null, language: string, default_style: Style, context_description: string | null, captions: Array<Caption>, speakers: Array<Speaker>, glossary: Array<GlossaryTerm>, 
/**
 * AI-generated social clips carved from the talk (SundayEdit).
 */
clips: Array<Clip>, 
/**
 * Short AI summary of the whole talk (SundayEdit).
 */
talk_summary: string | null, 
/**
 * Configurable export pipeline settings (format, burn-in, style).
 */
export_config: ExportConfig, 
/**
 * Editable project metadata (title, description, proper-noun hints).
 */
project_meta: ProjectMeta, created_at: number, updated_at: number, };
