// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-editable project metadata: title, video description (used as AI
 * context), glossary names for Whisper priming, and preferred language.
 */
export type ProjectMeta = { 
/**
 * Human-readable title (overrides the bare filename in the UI).
 */
title: string, 
/**
 * Prose description of the video — fed to AI as context.
 */
description: string, 
/**
 * Comma-separated list of proper nouns / glossary hints for Whisper.
 */
proper_nouns: string, 
/**
 * Transcription/translation language: "auto" | ISO 639-1 code
 */
language: string, };
