// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Caption } from "./Caption";
import type { GlossaryTerm } from "./GlossaryTerm";
import type { Speaker } from "./Speaker";
import type { Style } from "./Style";

export type Project = { id: string, name: string, video_path: string, video_content_hash: string, video_duration_ms: number, video_width: number, video_height: number, video_fps: number, audio_wav_path: string | null, language: string, default_style: Style, context_description: string | null, captions: Array<Caption>, speakers: Array<Speaker>, glossary: Array<GlossaryTerm>, created_at: number, updated_at: number, };
