// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipPlan } from "./ClipPlan";

/**
 * The reviewable storyboard handed back to the operator. `used_ai` tells the
 * UI whether these came from Claude or the keyless heuristic, so it can label
 * the source honestly.
 */
export type ReelStoryboard = { plan: ClipPlan, 
/**
 * True when Claude produced the clips; false when the heuristic did.
 */
used_ai: boolean, 
/**
 * Set when the AI path was attempted but failed (key present, call errored)
 * — the UI can surface it while still showing the heuristic fallback.
 */
ai_error: string | null, };
