// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of the batch render — surfaced after "Render all" finishes (or is
 * cancelled), so a partial success is visible.
 */
export type ReelRenderResult = { 
/**
 * Output paths that rendered successfully.
 */
rendered: Array<string>, 
/**
 * (item id, error message) for items that failed — one bad clip does not
 * abort the whole batch.
 */
failed: Array<[string, string]>, 
/**
 * True if the operator cancelled partway.
 */
cancelled: boolean, };
