// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Streamed to the UI as the batch render queue advances. Mirrors the
 * `DownloadProgress` shape (completed/total + fraction) plus the current item.
 */
export type ReelRenderProgress = { 
/**
 * Items finished (succeeded or failed) so far.
 */
completed: number, 
/**
 * Total items in the batch.
 */
total: number, 
/**
 * 0..1, or null when total is 0.
 */
fraction: number | null, 
/**
 * The item id currently rendering (or just finished), for the UI to
 * highlight a row. `None` once the batch is done.
 */
current_item_id: string | null, 
/**
 * Items that failed to render (e.g. ffmpeg missing). Reported so a partial
 * success is still surfaced — one bad clip doesn't sink the batch.
 */
failed: number, };
