// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReflowIssue = { caption_id: string, 
/**
 * "cps" | "line_length" | "line_count" | "min_duration"
 */
kind: string, 
/**
 * The offending measured value (CPS, longest line length, line count, or duration ms).
 */
value: number, 
/**
 * The limit it broke.
 */
limit: number, 
/**
 * Human-readable one-liner for the UI.
 */
message: string, };
