// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReflowConfig = { 
/**
 * Max readable characters-per-second. Broadcast/Netflix adult default 17.
 */
max_cps: number, 
/**
 * Max characters on a single line before it must wrap. BBC uses 37–40.
 */
max_chars_per_line: number, 
/**
 * Max lines visible at once (2 is the broadcast standard).
 */
max_lines: number, 
/**
 * Minimum on-screen time in ms. Below this a caption flashes (Netflix 833ms ≈ 5/6 s).
 */
min_duration_ms: number, };
