// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Clip } from "./Clip";
import type { ExportPreset } from "./ExportPreset";

/**
 * One concrete render job: a specific clip burned in at a specific platform
 * preset, written to `output_path`. The atomic unit of the batch queue.
 */
export type RenderItem = { 
/**
 * Stable id: `<clip_id>__<preset_id>`. Used to report per-item progress.
 */
id: string, clip: Clip, preset: ExportPreset, 
/**
 * Absolute output path (under the chosen output directory).
 */
output_path: string, };
