// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RenderItem } from "./RenderItem";

/**
 * The full fanned-out plan the operator confirms before "Render all".
 */
export type RenderPlan = { items: Array<RenderItem>, 
/**
 * Total = clips × platforms.
 */
total: number, };
