// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretProvider } from "./SecretProvider";

export type SecretStatus = { provider: SecretProvider, present: boolean, };
