// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Providers whose API keys we store. Anthropic powers the AI features today;
 * the cloud-ASR providers are here so the same store is ready when their
 * transcription path is wired.
 */
export type SecretProvider = "anthropic" | "open-ai" | "assembly-ai" | "deepgram";
