// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscribedWord } from "./TranscribedWord";

export type Segment = { start_ms: number, end_ms: number, words: Array<TranscribedWord>, };
