// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Style } from "./Style";

export type StylePreset = { style: Style, 
/**
 * Grouping for the gallery: "Broadcast", "Social", "Cinema", ...
 */
category: string, description: string, };
