// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationSpec } from "./AnimationSpec";

export type Style = { id: string, name: string, font_family: string, font_size_px: number, font_weight: number, italic: boolean, color_fg: string, outline_color: string, outline_width_px: number, shadow_color: string, shadow_offset_x: number, shadow_offset_y: number, shadow_blur: number, background_color: string | null, background_padding_px: number, background_radius_px: number, align_h: string, align_v: string, anchor: string, max_width_pct: number, line_spacing: number, letter_spacing: number, animation: AnimationSpec | null, };
