// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A proposed glossary entry, returned to the UI for review.
 */
export type SuggestedTerm = { 
/**
 * Canonical spelling we want in the output.
 */
term: string, 
/**
 * Likely misrecognitions to auto-correct to `term`.
 */
aliases: Array<string>, 
/**
 * One short sentence on why it's worth a glossary entry.
 */
reason: string, };
