// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuggestionKind } from "./SuggestionKind";

/**
 * One proposed change, returned to the UI as a review-queue item. Applied
 * only if the user accepts it.
 */
export type Suggestion = { 
/**
 * Accept "id" too — some models prefer the shorter key.
 */
caption_id: string, kind: SuggestionKind, 
/**
 * The full proposed replacement text for the caption.
 */
suggestion: string, 
/**
 * One short sentence on why.
 */
reasoning: string, };
