// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Minimal text spec for Text/Graphic overlay items.
 */
export type TextSpec = { text: string, style_id: string | null, };
