// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Effect } from "./Effect";
import type { TextSpec } from "./TextSpec";
import type { TimelineItemKind } from "./TimelineItemKind";
import type { Transform } from "./Transform";
import type { Transition } from "./Transition";

/**
 * A single clip placed on a track. `in_ms`/`out_ms` index into the source
 * media; `timeline_start_ms` is where it sits on the timeline.
 */
export type TimelineItem = { id: string, track_id: string, kind: TimelineItemKind, source_media_id: string | null, in_ms: number, out_ms: number, timeline_start_ms: number, speed: number, transform: Transform, effects: Array<Effect>, transition_in: Transition | null, text: TextSpec | null, enabled: boolean, locked: boolean, };
