// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackKind } from "./TrackKind";

/**
 * A horizontal lane on the timeline. `index` is the stacking order (0 = bottom).
 */
export type Track = { id: string, kind: TrackKind, name: string, index: number, enabled: boolean, locked: boolean, muted: boolean, solo: boolean, };
