// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CropRect } from "./CropRect";

/**
 * Geometric transform for a timeline item, as fractions of the output frame
 * (resolution-independent). `Default` is the identity transform.
 */
export type Transform = { x: number, y: number, scale: number, rotation_deg: number, opacity: number, crop: CropRect | null, };
