// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranscribedWord = { text: string, start_ms: number, end_ms: number, 
/**
 * Already normalized to 0..100 via `confidence::*`.
 */
confidence: number, };
