// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Segment } from "./Segment";

/**
 * A fully normalized transcription result. The unit the rest of the app
 * consumes, regardless of backend.
 */
export type Transcript = { language: string, segments: Array<Segment>, 
/**
 * Which backend produced this — shown in the UI ("Local · large-v3-turbo").
 */
backend: string, };
