// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Segment } from "./Segment";

/**
 * Progress events streamed to the UI during a run.
 */
export type TranscribeProgress = { "kind": "preparing" } | { "kind": "running", fraction: number, } | { "kind": "segment", fraction: number, segment: Segment, } | { "kind": "done" };
