// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A transition (e.g. crossfade) at the leading edge of a timeline item.
 */
export type Transition = { kind: string, duration_ms: number, };
