// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Caption } from "./Caption";
import type { LengthWarning } from "./LengthWarning";

/**
 * Result of a translation pass: the translated caption track (timings
 * preserved), the target language, and any reading-speed warnings.
 */
export type TranslationResult = { target_language: string, captions: Array<Caption>, warnings: Array<LengthWarning>, };
