// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A language offered in the target picker. Claude handles many more; this
 * is just a convenient curated list.
 */
export type TranslationLanguage = { code: string, name: string, };
