// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output video codec. We expose the common, sensible choices.
 */
export type VideoCodec = "h264" | "h265";
