// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MediaKind } from "./MediaKind";

export type VideoMetadata = { duration_ms: number, width: number, height: number, fps: number, video_codec: string | null, audio_codec: string | null, audio_channels: number | null, audio_sample_rate: number | null, container: string | null, kind: MediaKind, };
