// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Peak } from "./Peak";

/**
 * Multi-resolution peak data. `levels[0]` is the coarsest (whole file in
 * few buckets); higher indices are finer. The editor picks the level
 * closest to the current pixel-per-second zoom.
 */
export type WaveformData = { sample_rate: number, total_samples: number, 
/**
 * One entry per zoom level; each is a Vec<Peak>.
 */
levels: Array<Array<Peak>>, };
