// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WhisperModel } from "./WhisperModel";

export type WhisperModelInfo = { model: WhisperModel, 
/**
 * ggml filename, e.g. "ggml-large-v3-turbo.bin".
 */
filename: string, 
/**
 * Approx download size in MB — shown so users on slow links can choose.
 */
approx_mb: number, 
/**
 * Download URL (Hugging Face ggml repo).
 */
url: string, 
/**
 * One-line tradeoff description for the picker.
 */
description: string, 
/**
 * Whether it handles non-English well.
 */
multilingual: boolean, 
/**
 * The size we recommend by default.
 */
recommended: boolean, };
