// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternateRead } from "./AlternateRead";

export type Word = { text: string, start_ms: number, end_ms: number, 
/**
 * 0–100 normalized confidence from ASR.
 */
confidence: number, 
/**
 * User has changed this word from the ASR output.
 */
edited: boolean, 
/**
 * User has confirmed — do not surface as uncertain even if confidence is low.
 */
locked: boolean, 
/**
 * AI polish (Phase 4.1) adjusted this word's punctuation/casing. Not a
 * content change, so it does NOT trust the word like `edited` does —
 * it only drives the "polished" dot in the editor.
 */
polished: boolean, 
/**
 * Top alternates from ASR (max 3).
 */
alternates: Array<AlternateRead>, };
